language: cpp
compiler: gcc
os: linux
addons:
  apt:
    sources:
     - ubuntu-toolchain-r-test
    packages:
     - gcc-4.9
     - g++-4.9
before_install:
 - sudo apt-get update -q
 - sudo apt-get install -yq gcc-4.9 g++-4.9
 - sudo apt-get install -yq libgmp-dev libmpfr-dev libmpc-dev flex
before_script:
 - export CC=gcc-4.9
 - export CXX=g++-4.9
 - cd gcc
script:
 - ./configure --enable-languages=c,c++ --disable-multilib --silent
 - make
 - make test
branches:
  only:
   - master
